apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-delete-task-deployment
spec:
  replicas: 1
  selector:
    matchExpressions: 
      - key: app
        operator: In
        values: 
        - todo-delete-task
  strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: todo-delete-task
    spec:
      containers:
      - name: delete-task
        env:
          - name: CONNECTION_STRING
            value: "Driver={ODBC Driver 17 for SQL Server};Server=tcp:subhojit-dbserver.database.windows.net,1433;Database=subbhojit-db;Uid=adminuser;Pwd=GQ4C9q`p[9A£;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
        image: subho9407/todobackend-delete_task
        ports:
        - containerPort: 8000
